/* Auto-generated by genmsg_cpp for file /vol/ORB_SLAM3/Examples/ROS/ORB_SLAM3/msg/PoseStampedArray.msg */
#ifndef ORB_SLAM3_MESSAGE_POSESTAMPEDARRAY_H
#define ORB_SLAM3_MESSAGE_POSESTAMPEDARRAY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/PoseStamped.h"

namespace ORB_SLAM3
{
template <class ContainerAllocator>
struct PoseStampedArray_ {
  typedef PoseStampedArray_<ContainerAllocator> Type;

  PoseStampedArray_()
  : header()
  , poses()
  {
  }

  PoseStampedArray_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , poses(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _poses_type;
  std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  poses;


  typedef boost::shared_ptr< ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator>  const> ConstPtr;
}; // struct PoseStampedArray
typedef  ::ORB_SLAM3::PoseStampedArray_<std::allocator<void> > PoseStampedArray;

typedef boost::shared_ptr< ::ORB_SLAM3::PoseStampedArray> PoseStampedArrayPtr;
typedef boost::shared_ptr< ::ORB_SLAM3::PoseStampedArray const> PoseStampedArrayConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ORB_SLAM3

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6227e2b7e9cce15051f669a5e197bbf7";
  }

  static const char* value(const  ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6227e2b7e9cce150ULL;
  static const uint64_t static_value2 = 0x51f669a5e197bbf7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ORB_SLAM3/PoseStampedArray";
  }

  static const char* value(const  ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
geometry_msgs/PoseStamped[] poses\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.poses);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct PoseStampedArray_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ORB_SLAM3::PoseStampedArray_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORB_SLAM3_MESSAGE_POSESTAMPEDARRAY_H

